"""Second  Migration

Revision ID: 1f66357e344f
Revises: 0f4aaf7bf233
Create Date: 2019-07-12 10:53:51.991007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f66357e344f'
down_revision = '0f4aaf7bf233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('adress', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('contact', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'adress')
    # ### end Alembic commands ###
